apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-api
spec:
  selector:
    matchLabels:
      app: dev-api
  replicas: 3
  template:
    metadata:
      labels:
        app: dev-api
    spec:
      containers:
        - name: dev-api
          image: danielneset/idata2306dev:dev-5f6d2c6acba4bb937dfb7ffb558fbbf3a2447710
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "dev"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "dbeaver"
