apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-api
spec:
  selector:
    matchLabels:
      app: dev-api
  replicas: 3
  template:
    metadata:
      labels:
        app: dev-api
    spec:
      containers:
      - name: dev-api
        image: danielneset/idata2306dev:dev-dd4c956206138438c20cfc7f9816ba93d191c779
        ports:
        - containerPort: 8080
          protocol: TCP
