apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-api
spec:
  selector:
    matchLabels:
      app: dev-api
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-api
    spec:
      hostNetwork: true
      containers:
        - name: dev-api
          image: danielneset/idata2306dev:dev-26f930708bfcc621a095dc40f154b36a4412cc24
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: PORT
              value: "8081"
            - name: DDL
              value: "update"
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "dev"
            - name: DB_USERNAME
              value: "devUser"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devpass
                  key: secret-key
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jwtdev
                  key: secret-key

