apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-api
spec:
  selector:
    matchLabels:
      app: dev-api
  replicas: 3
  template:
    metadata:
      labels:
        app: dev-api
    spec:
      containers:
      - name: dev-api
        image: danielneset/idata2306dev:dev-d423672db6ecb5865af159f5f9362ff1fb5b07df
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DB_HOST
          value: "host.docker.internal"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "dev"
