apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dev-frontend
spec:
  ingressClassName: nginx
  rules:
    - host: dev.flightfinder.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-web-service
                port:
                  number: 3000
