apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-web
spec:
  selector:
    matchLabels:
      app: dev-web
  replicas: 3
  template:
    metadata:
      labels:
        app: dev-web
    spec:
      containers:
        - name: dev-web
          image: danielneset/idata2301dev:dev-web-f722f6ec3616c36a3b5a591b9fc9efc755cc0bd2
          ports:
            - containerPort: 3000
              protocol: TCP
