apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-api
spec:
  selector:
    matchLabels:
      app: prod-api
  replicas: 1
  template:
    metadata:
      labels:
        app: prod-api
    spec:
      hostNetwork: true
      containers:
      - name: prod-api
        image: danielneset/idata2306:prod-67afea71b12cd142c18fb035e914f9cc055c1379
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: PORT
            value: "8080"
          - name: DDL
            value: "update"
          - name: DB_HOST
            value: "localhost"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "prod"
          - name: DB_USERNAME
            value: "prodUser"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prodpass
                key: secret-key
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: jwtprod
                key: secret-key
