apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod2306
spec:
  selector:
    matchLabels:
      app: prod2306
  replicas: 3
  template:
    metadata:
      labels:
        app: prod2306
    spec:
      containers:
      - name: prod2306
        image: danielneset/idata2306:prod-8fff1b2eb4656912230c92b2fbb6d3d29b72c605
        ports:
        - containerPort: 8080
          protocol: TCP
