apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-api
spec:
  selector:
    matchLabels:
      app: prod-api
  replicas: 3
  template:
    metadata:
      labels:
        app: prod-api
    spec:
      containers:
      - name: prod-api
        image: danielneset/idata2306
        ports:
        - containerPort: 8080
          protocol: TCP
