apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prod-backend
spec:
  ingressClassName: nginx
  rules:
  - host: api.flightfinder.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-service
            port:
              number: 8080