apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-web
spec:
  selector:
    matchLabels:
      app: prod-web
  replicas: 3
  template:
    metadata:
      labels:
        app: prod-web
    spec:
      containers:
      - name: prod-web
        image: danielneset/idata2301:prod-web-b36b3d051339aa4772f65e4df0dd702f5cd631bc
        ports:
        - containerPort: 3000
          protocol: TCP
