apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-web
spec:
  selector:
    matchLabels:
      app: prod-web
  replicas: 3
  template:
    metadata:
      labels:
        app: prod-web
    spec:
      containers:
      - name: prod-web
        image: danielneset/idata2306:prod-22ff19e1bf7a31632427dc7605d3fee2806319d4
        ports:
        - containerPort: 3000
          protocol: TCP
