apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-web
spec:
  selector:
    matchLabels:
      app: prod-web
  replicas: 3
  template:
    metadata:
      labels:
        app: prod-web
    spec:
      containers:
      - name: prod-web
        image: danielneset/idata2301:prod-web-43fb1c1702d2976f99390733a24bc3d1375bd50b
        ports:
        - containerPort: 3000
          protocol: TCP
