apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-web
spec:
  selector:
    matchLabels:
      app: prod-web
  replicas: 3
  template:
    metadata:
      labels:
        app: prod-web
    spec:
      containers:
      - name: prod-web
        image: danielneset/idata2301:prod-web-3499e99b74f10fbc0a7d9f09918d2b3f87003953
        ports:
        - containerPort: 3000
          protocol: TCP
